# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - PS-285-Add-Angular-to-MVC-Applications

# 04/11/2022 12:56 am - SSN - Add default directory for Angular.  Originally used by msbuild

#defaults:
#  run:
#    working-directory: published

on:
  push:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    
#    - name: create test directory
#      run: |
#        mkdir temp20220411
#        write-output "test" | Out-File temp20220411/test101.txtt
       
    - name: Test startup dir
      run: |
         $exclude =  @('windows', 'microsoft', 'az', 'program files', 'inetpub', 'drivers', 'packages', 'node_modules')
         function excl  ($f) {  -not (  $f -match ( $exclude -join '|' ))  }
         get-childitem -path "d:\" -recurse -directory| where { excl -f $_.fullname }


    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages [20220922-0616]
      run: nuget restore

 
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: npm install
      run: npm install

# 11/09/2022 09:55 pm - SSN - Move after .NET build

#    - name: npm run build:prod
#      run: |
#        npm run build:prod 
#        xcopy dist_1109\*.* \published\dist_1109\*.*


#    - name: Test node dir
#      run: |
#         $exclude =  @('windows', 'microsoft', 'az', 'program files', 'inetpub', 'drivers', 'packages', 'node_modules')
#         function excl  ($f) {  -not (  $f -match ( $exclude -join '|' ))  }
#         get-childitem -path "d:\" -recurse -directory| where { excl -f $_.fullname }




# 09/22/2022 06:16 am - SSN - Move after building Angular - Was after "Restore NuGet Packes" [20220922-0616]
# 11/09/2022 09:57 pm - SSN - Change name
#    - name: Publish to folder
    - name: MSBuild project
# 09/19/2022 04:55 am - SSN - Containerized app.  docker-compose.dcproj.  Specify ptc.csproj. 
#      run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
      run: msbuild ptc.csproj -property:Configuration=Release  /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\" 

    - name: Test .net dir
      run: |
         $exclude =  @('windows', 'microsoft', 'az', 'program files', 'inetpub', 'drivers', 'packages', 'node_modules')
         function excl  ($f) {  -not (  $f -match ( $exclude -join '|' ))  }
         get-childitem -path "d:\" -recurse -directory| where { excl -f $_.fullname }




# 11/09/2022 09:55 pm - SSN - Move after .NET build

    - name: npm run build:prod
      run: |
        npm run build:prod 
        xcopy dist_1109\*.* \published\dist_1109\*.*


    - name: Test node dir
      run: |
         $exclude =  @('windows', 'microsoft', 'az', 'program files', 'inetpub', 'drivers', 'packages', 'node_modules')
         function excl  ($f) {  -not (  $f -match ( $exclude -join '|' ))  }
         get-childitem -path "d:\" -recurse -directory| where { excl -f $_.fullname }


    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: ASP-app
        path: '/published/**'

  deploy:
    runs-on: 'windows-latest'
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: ASP-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PS-285-Add-Angular-to-MVC-Applications'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6918a4cd4ba04bd79a70212a7fd07d31 }}
        package: .
