# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - PS-285-Add-Angular-to-MVC-Applications

# 04/11/2022 12:56 am - SSN - Add default directory for Angular.  Originally used by msbuild

defaults:
  run:
    working-directory: ./published

on:
  push:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    
    - name: create test directory
      run: |
        mkdir ./published
        mkdir temp20220411
        write-output "test" | Out-File temp20220411/test101.txtt
       

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore

    - name: Publish to folder
      run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder # /p:_PackageTempDir="\published\"

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: npm install
      run: npm install

    - name: npm run build:prod
      run: npm run build:prod 


    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: ASP-app
        path: '/published/**'

  deploy:
    runs-on: 'windows-latest'
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: ASP-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PS-285-Add-Angular-to-MVC-Applications'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6918a4cd4ba04bd79a70212a7fd07d31 }}
        package: .
